apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth 
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::521725812311:user/cloud-project    # Update as needed with your IAM user ARN
      username: cloud-project    # Update as needed with your desired Kubernetes username
      groups:
        - system:masters    # Gives admin access to cluster