apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dev-shopwise-eks-secret-provider-class
  namespace: dev-shopwise-eks-namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:521725812311:secret:dev-shopwise-app-secret-5uOCwp"
        objectAlias: "dev-shopwise-eks-secrets"
  secretObjects:
    - secretName: dev-shopwise-app-secret      # This creates a K8s Secret from your AWS secret
      type: Opaque
      data:
        - objectName: "arn:aws:secretsmanager:us-east-1:521725812311:secret:dev-shopwise-app-secret-5uOCwp"
          key: password

